python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -c rdkit -n test-environment python=$TRAVIS_PYTHON_VERSION rdkit
  - conda activate test-environment
  - python -m pip install .

script:
  # Your test script goes here
