name: chemgraph
channels:
  - conda-forge
  - anaconda
dependencies:
  - numpy>=1.19
  - scipy>=1.6
  - pandas>=1.1
  - networkx
  - tensorflow==2.4.1
  - nose>=1.0
  - flake8
  - rdkit
  - pip
  - pip:
    - lz4
    - cram
    - tensorflow-datasets
    - jaxlib==0.1.60
    - jax==0.2.10
    - tfp-nightly[jax]
    - typing_extensions
    - coverage
    - coveralls
    - black
    - mypy
    - pylint
